spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE

management:
 endpoints:
   web:
     exposure:
       include: "*"